---
version: "2.4"
services:
  hello_world:
    image: hello-world:latest
    networks:
      macvlan0:
        ipv4_address: 192.168.178.223

networks:
  macvlan0:
    name: macvlan0
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.178.0/24"
          ip_range: "192.168.178.208/28"
          gateway: "192.168.178.1"
