---
version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    domainname: home.arpa
    hostname: prometheus
    networks:
      macvlan0:
        ipv4_address: 192.168.178.211
    volumes:
      - "/volume1/docker/analytics/prometheus:/etc/prometheus:rw"
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://192.168.178.211:9090 || exit 1

  grafana:
    image: grafana/grafana-oss
    user: "0"
    container_name: grafana
    domainname: home.arpa
    hostname: grafana
    networks:
      macvlan0:
        ipv4_address: 192.168.178.212
    volumes:
      - "/volume1/docker/analytics/grafana:/var/lib/grafana:rw"
    restart: unless-stopped
    env_file:
      - grafana.env
    healthcheck:
      test: curl --fail http://192.168.178.212/api/health || exit 1

networks:
  macvlan0:
    external: true
