---
version: "3.9"
services:
  pihole:
    image: pihole/pihole
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - "/volume1/docker/pihole/dnsmasq.d:/etc/dnsmasq.d:rw"
      - "/volume1/docker/pihole/pihole:/etc/pihole:rw"
    restart: unless-stopped
    env_file:
      - pihole.env
    labels:
      - arpa.home.description="Pi-hole DNS Server"
      - arpa.home.category="Network"
