---
version: "3.9"
services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - "/volume1/docker/pihole/dnsmasq.d:/etc/dnsmasq.d:rw"
      - "/volume1/docker/pihole/pihole:/etc/pihole:rw"
    restart: unless-stopped
    env_file:
      - pihole.env
