---
version: "3.9"
services:
  calibre:
    image: ghcr.io/linuxserver/calibre-web
    ports:
      - "8083:8083"
    volumes:
      - "/volume1/docker/calibre/config:/config:rw"
      - "/volume1/docker/calibre/library:/books:rw"
    restart: unless-stopped
    env_file:
      - calibre.env
    healthcheck:
      test: curl --fail http://localhost:8083 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - arpa.home.description="Calibre Web - Ebook library"
      - arpa.home.category="Media"
