---
version: "3.9"
services:
  unbound:
    image: "mvance/unbound:latest"
    container_name: unbound
    ports:
      - "5335:5335/tcp"
      - "5335:5335/udp"
    volumes:
      - "/volume1/docker/unbound/unbound:/opt/unbound/etc/unbound:rw"
    restart: unless-stopped
