---
version: "3.9"
services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    domainname: home.arpa
    hostname: portainer
    networks:
      macvlan0:
        ipv4_address: 192.168.178.210
    volumes:
      - "/volume1/docker/portainer/data:/data:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider --no-check-certificate https://192.168.178.210 || exit 1
    entrypoint: /portainer --bind :80 --bind-https :443

networks:
  macvlan0:
    external: true
