---
version: "3.9"
services:
  portainer:
    image: portainer/portainer-ce:alpine
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - "/volume1/docker/portainer/data:/data:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider --no-check-certificate https://localhost:9443 || exit 1
    labels:
      - arpa.home.description="Portainer - Docker Management UI"
      - arpa.home.category="Containers"
